# Generated by Django 5.1.2 on 2024-10-22 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsecundaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnot',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='frase',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'frases'},
        ),
        migrations.AlterModelTable(
            name='alumnot',
            table='Alumnos',
        ),
    ]
